version: 2
vm_settings:
  docker:
    - image: circleci/node:latest-browsers
  working_directory: ~/app
install_restore_cache:
  name: Restore cached dependencies
  keys:
    - dependencies-{{ checksum "yarn.lock" }}
    - dependencies
install_run:
  name: Install dependencies with Yarn, purely from the lockfile
  command: yarn install --frozen-lockfile
install_save_cache:
  name: Cache installed dependencies
  paths:
    - ~/.cache
  key: dependencies-{{ checksum "yarn.lock" }}
jobs:
  test:
    docker:
      - image: circleci/node:latest-browsers
    working_directory: ~/app
    steps:
      - checkout
      - restore_cache:
          name: Restore cached dependencies
          keys:
            - dependencies-{{ checksum "yarn.lock" }}
            - dependencies
      - run:
          name: Install dependencies with Yarn, purely from the lockfile
          command: yarn install --frozen-lockfile
      - save_cache:
          name: Cache installed dependencies
          paths:
            - ~/.cache
          key: dependencies-{{ checksum "yarn.lock" }}
      - run:
          name: Run tests
          command: sudo apt-get install libgconf-2-4 && yarn test:ci
      - store_artifacts:
          path: tests/unit/coverage
      - store_artifacts:
          path: tests/e2e/videos
      - store_artifacts:
          path: tests/e2e/screenshots
  build:
    docker:
      - image: circleci/node:latest-browsers
    working_directory: ~/app
    steps:
      - checkout
      - restore_cache:
          name: Restore cached dependencies
          keys:
            - dependencies-{{ checksum "yarn.lock" }}
            - dependencies
      - run:
          name: Install dependencies with Yarn, purely from the lockfile
          command: yarn install --frozen-lockfile
      - save_cache:
          name: Cache installed dependencies
          paths:
            - ~/.cache
          key: dependencies-{{ checksum "yarn.lock" }}
      - run:
          name: Build for production
          command: yarn build:ci
      - store_artifacts:
          path: dist
workflows:
  version: 2
  test_and_deploy:
    jobs:
      - test
      - build
